# Generated by Django 3.2.5 on 2021-07-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStandingsModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('family_name', models.CharField(blank=True, max_length=100, null=True)),
                ('dob', models.CharField(blank=True, max_length=100, null=True)),
                ('nationality', models.CharField(blank=True, max_length=200, null=True)),
                ('code', models.CharField(blank=True, max_length=5, null=True)),
                ('permanent_number', models.CharField(blank=True, max_length=500, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('points', models.IntegerField(default=0)),
                ('wins', models.CharField(blank=True, max_length=50, null=True)),
                ('constructor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cons_nat', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RaceResults',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
